version: 0.2

phases:
  build: 
    commands: 
      - echo Entered the build phase
      - mvn clean package
  post_build: 
    commands: 
      - build completed successfully
artifacts:  
  files: 
    - target/java-art.war
  discard-paths: yes
  